[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.12.0",
    "chz>=0.4.0",
    "datasets>=4.4.1",
    "dotenv>=0.9.9",
    "jupyter>=1.1.1",
    "peft>=0.18.0",
    "tinker>=0.3.0",
    "torch>=2.9.1",
    "transformers>=4.57.3",
    "trl>=0.25.1",
]
